<?php

/**
 * Station API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ayhanyunt@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Station API
 * @version 1.0.0
 */

$app->get('/', function () use ($app) {
    return $app->version();
});

/**
 * POST createStation
 * Summary: create a new station
 * Notes: Create new station with the given parameters, insert it to database and returns the created station information.
 * Output-Formats: [application/json]
 */
$app->POST('/ayhanyunt12/MeteorolojiAPI/1.0.0/station', 'DevelopersApi@createStation');
/**
 * PUT updateStation
 * Summary: update existing station
 * Notes: Update the station with given id and return the new station informations.
 * Output-Formats: [application/json]
 */
$app->PUT('/ayhanyunt12/MeteorolojiAPI/1.0.0/station', 'DevelopersApi@updateStation');
/**
 * DELETE stationIdDelete
 * Summary: Delete a user by public_id
 * Notes: 

 */
$app->DELETE('/ayhanyunt12/MeteorolojiAPI/1.0.0/station/{id}', 'DevelopersApi@stationIdDelete');
/**
 * GET stationIdGet
 * Summary: Get a user by ID
 * Notes: 

 */
$app->GET('/ayhanyunt12/MeteorolojiAPI/1.0.0/station/{id}', 'DevelopersApi@stationIdGet');
/**
 * GET getStations
 * Summary: get all station information
 * Notes: Return a json with all station&#39;s information
 * Output-Formats: [application/json]
 */
$app->GET('/ayhanyunt12/MeteorolojiAPI/1.0.0/stations', 'DevelopersApi@getStations');

